### ISSUE TITLE
Convert layout to UI design Wireframe 

### ISSUE THREAD

**Issue by AasthaMehtaTech** [CoolCoderz/atRentals#2]
It would be good to have a wireframe (Preferably Figma) designed so that it becomes easy developing the site.
- Enhancements requested: Simple, Creative UI (You're free to choose any Light Themed Color Resources, contact aasthamehta2704@gmail.com or akrishna17d@gmail.com for any further information / doubts.) 
- Note: The layout (framer) link is available in Readme.md
- You can find the other pages ( give, rent, how this works, etc) by clicking on top left drop down menu which says Name: Home.
- Regarding design (& other carousel/ img /style resources) you are free to choose any that seems visually pleasing for a book renting site.
- Pages to be designed:
	- [] Home
	- [] Give/Lease 
	- [] Rent
	- [] Books
	- [] How this works 
	- [] About Us

**Comment by AnjanaMA** [comment]
I'm interested in taking this up.

**Comment by AasthaMehtaTech** [comment]
Yeah @AnjanaMA, the issue is up for grabs go ahead! You can contact us for any UI related doubts/ suggestions.
